license.application/Controllers/HomeController.cs
using license.application.Data;
using license.application.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace license.application.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private ApplicationDbContext _applicationDbContext;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext applicationDbContext)
        {
            _logger = logger;
            _applicationDbContext = applicationDbContext;
        }

        public async Task<IActionResult> Index()
        {
            var machines = await _applicationDbContext.Machines.Include(m => m.License).OrderByDescending(m => m.Id).ToListAsync();
            return View(machines);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public ActionResult Edit(int id)
        {
            var machine = _applicationDbContext.Machines.FirstOrDefault(m => m.Id == id);
            var license = _applicationDbContext.License.Where(l => l.Machine == null || l.Machine.Id == id).ToList();

            return View(new MachineViewModel() { Machine = machine, Licenses = license});
        }

        // POST: License/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Machine machine)
        {
            try
            {
                if (machine.LicenseId.HasValue)
                {
                    var license = await _applicationDbContext.License.FirstOrDefaultAsync(l => l.Id == machine.LicenseId.Value);
                    machine.Active = license.IsActive();
                }
                else machine.Active = false;

                _applicationDbContext.Machines.Update(machine);
                _applicationDbContext.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                return RedirectToAction(nameof(Index));
            }
        }

        // GET: LicenseController/Delete/5
        public ActionResult Delete(int id)
        {
            var machine = _applicationDbContext.Machines.FirstOrDefault(l => l.Id == id);
            _applicationDbContext.Machines.Remove(machine);

            _applicationDbContext.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
    }
}

license.application/Controllers/LicenseController.cs
using license.application.Data;
using license.application.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace license.application.Controllers
{
    [Authorize]
    public class LicenseController : Controller
    {
        private ApplicationDbContext _applicationDbContext;

        public LicenseController(ApplicationDbContext applicationDbContext)
        {
            _applicationDbContext = applicationDbContext;
        }

        // GET: License
        public async Task<ActionResult> Index()
        {
            var license = await _applicationDbContext.License.Include(l => l.Machine).OrderByDescending(l => l.CreatedUtc).ToListAsync();

            return View(license);
        }

        // GET: License/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: License/Create
        public ActionResult Create(int? id)
        {
            License newlicense = null;

            if (id.HasValue)
                newlicense = _applicationDbContext.License.FirstOrDefault(l => l.Id == id.Value);
            else
              newlicense = new License() {
                Key = Guid.NewGuid().ToString(),
                ExpireDate = DateTime.Now.AddDays(90)
                };
            
            return View(newlicense);
        }

        // POST: License/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(License license)
        {
            try
            {
                if(license.Id > 0)
                {
                    _applicationDbContext.License.Update(license);
                    var machine = await _applicationDbContext.Machines.FirstOrDefaultAsync(m => m.LicenseId == license.Id);
                    if (machine != null)
                    {
                        machine.Active = license.IsActive();
                        _applicationDbContext.Machines.Update(machine);
                    }
                }
                else 
                    await _applicationDbContext.License.AddAsync(license);
                
                _applicationDbContext.SaveChanges();
                
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: License/Edit/5
        public ActionResult Edit(int id)
        {
           var newlicense = _applicationDbContext.License.FirstOrDefault(l => l.Id == id);

            return View("Create", newlicense);
        }

        // POST: LicenseController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: LicenseController/Delete/5
        public ActionResult Delete(int id)
        {
            var newlicense = _applicationDbContext.License.FirstOrDefault(l => l.Id == id);
            _applicationDbContext.License.Remove(newlicense);

            _applicationDbContext.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        // POST: LicenseController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

license.application/Views/Home/Edit.cshtml
@model license.application.Models.MachineViewModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div style="margin-bottom: 20px;" class="border-bottom">
    <h5 class="display-4 text-primary"><b style="font-size: 25px;">Edit/Create Customer</b></h5>
</div>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Machine.Id" class="form-control" hidden />
            <div class="form-group">
                <label asp-for="Machine.Name" class="control-label"></label>
                <input asp-for="Machine.Name" class="form-control" />
                <span asp-validation-for="Machine.Name" class="text-danger"></span>
            </div>
            <div class="form-group" style="margin-top: 10px;">
                <label asp-for="Machine.UniqueId" class="control-label"></label>
                <input asp-for="Machine.UniqueId" class="form-control" />
                <span asp-validation-for="Machine.UniqueId" class="text-danger"></span>
            </div>
            <div class="form-group form-check" style="margin-top: 10px;" hidden>
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Machine.Active" /> @Html.DisplayNameFor(model => model.Machine.Active)
                </label>
            </div>
            <div class="form-group" style="margin-top: 10px;">
                <label asp-for="Machine.LicenseId" class="control-label"></label>
                <select asp-for="Machine.LicenseId" class="form-control"
                        asp-items="@(new SelectList(Model.Licenses, nameof(License.Id), nameof(License.Key)))">
                    <option>Please select one</option>
                </select>
            </div>
            <div class="form-group" style="margin-top: 10px;">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div style="margin-top: 10px;">
    <a asp-action="Index">Back to List</a>
</div>

license.application/Views/Home/Index.cshtml
@model List<Machine>
@{
    ViewData["Title"] = "Home Page";
}

<div style="margin-bottom: 20px;" class="text-center border-bottom">
    <h5 class="display-4 text-primary"><b style="font-size: 25px;">Customer List</b></h5>
</div>

@*<button style="margin: 10px; float: right" type="button" class="btn btn-success float-right">Save</button>*@
<table class="table table-bordered table-hover table-striped">
    <thead>
        <tr class="table-primary">
            <th scope="col">Id</th>
            <th scope="col">Machine Name</th>
            <th scope="col">UniqueId</th>
            <th scope="col">License</th>
            <th scope="col">Active</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var item in Model)
            {
                <tr>
                    <td scope="row">@item.Id</td>
                    <td>@item.Name</td>
                    <td>@item.UniqueId</td>
                    <td>
                        @if (item.License != null)
                        {
                            <span> Key:</span><a style="margin-left: 5px;" asp-controller="License" asp-action="Edit" asp-route-id="@item.Id"> @item.License?.Key</a>
                            <p>Expired Date: @item.License?.ExpireDate.ToString("dd/MM/yyyy")</p>
                        }

                    </td>
                    <td>
                        <input type="checkbox" asp-for="@item.Active" disabled />

                    </td>
                    <td> <a style="margin-left: 5px;" asp-action="Edit" asp-route-id="@item.Id"><i class="fas fa-edit text-primary"></i></a></td>
                    <th>
                        <form method="Delete" asp-action="Delete" asp-route-id="@item.Id"
                              onclick="return confirm('Are you sure you want to delete this?')">
                            <button style="border: none; background: transparent;" type="submit"><i class="fas fa-trash-alt text-warning"></i></button>
                        </form>
                    </th>
                </tr>
            }
        }
    </tbody>
</table>

@section scripts{ 

    <script>
        $(document).ready(function () {
            $("input[type='checkbox']").change(function (e) {
                var id = $(this).closest('tr').children('td:first').text()
                $.ajax({
                    type: "PUT",
                    dataType: "json",
                    contentType: "application/json",
                    url: '/api/machine/' + id,

                    data: JSON.stringify({ })
                });
            });
        });

    </script>
}